route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'telegram-api'
receivers:
  - name: 'telegram-api'
    telegram_configs:
    - bot_token: '6460658473:AAHi03NFqR6CZmM4fPW9qhb8Tem2l7FFZSk'
      api_url: 'https://api.telegram.org'
      chat_id: -1002181936769
      parse_mode: ''
      message_thread_id: 2
      message: "🚨 Alertmanager 🚨\n--\n🔺 Alertname: {{ .GroupLabels.alertname}}\n🔺 Severity: {{ .CommonLabels.severity }}\n📌 {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
