global:
  scrape_interval: 15s # Интервал опроса всех целей по умолчанию
  evaluation_interval: 15s # Интервал для правил оценки

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "localhost:9093"

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['89.169.133.88:9100']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['89.169.133.88:9104']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://site.aleksandrfaer.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: site.aleksandrfaer.ru
      - target_label: __address__
        replacement: localhost:9115  # Укажите правильный IP
